### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by yanyanshao** [massonix/tabula_muris_networks#1]
hi，
 the directory of data missing the file named ['Mus](url) musculus_consolidated.csv'

file 'tabula_muris_network_analysis.Rmd' need this file:

```{r}
# essential: df with essentiality status (essential or non-essential) for 
# over 9,000 mouse genes
essential <- read.csv(
  file = "data/Mus musculus_consolidated.csv", 
  header = TRUE
)

**Comment by massonix** [comment]
Hi @yanyanshao ,

Sorry, for the late reply, I didn't see your issue. I just uploaded the file you were missing.

Thanks and let me know if I can help with anything else.

Ramon
